name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  test-and-quality-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js with cache
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 4: Lint the code
      - name: Run Linter
        run: npm run lint

      # Step 5: Run unit tests with coverage
      - name: Run Unit Tests with Coverage
        run: npm run test:coverage
        env:
          CI: true

      # Step 6: Upload coverage reports as artifacts
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

      # Step 7: Publish Coverage to Codecov

      # Step 8: Generate Coverage Badge
      - name: Generate Coverage Badge
        uses: cicirello/jacoco-badge-generator@v3
        with:
          jacoco-coverage-json: ./coverage/lcov-report/index.html
          badge-path: ./coverage/badge.svg

      # Step 9: Perform Security Audit
      - name: Run Security Scan
        run: npm audit --audit-level=moderate

      # Step 10: Perform Dependency Vulnerability Check
      - name: Dependency Vulnerability Scan
        uses: anthonybruyant/dependency-review-action@v2

      # Step 11: Run Cypress Tests
      - name: Run Cypress Tests
        run: npm run cypress:run:workflow || true

      # Step 12: Upload Cypress Test Artifacts
      - name: Upload Cypress Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: cypress/results/
